apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frps.fullname" . }}
  labels:
    {{- include "frps.labels" . | nindent 4 }}
data:
  frps.toml: |
    {{- .Values.config | nindent 4 }}
    {{- if or .Values.auth.token .Values.auth.existingSecret }}
    auth.token = "{{ "{{ .Envs.FRP_AUTH_TOKEN }}" }}"
    {{- end }}
