{{- if and .Values.auth.token (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frps.fullname" . }}
  labels:
    {{- include "frps.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ .Values.auth.token | b64enc | quote }}
{{- end }}
