{{- if and .Values.storage.enabled (not .Values.storage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "goatcounter.fullname" . }}-data
  labels:
    {{- include "goatcounter.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
{{- end }}
